build(deps-dev): Update lint and test stack
Update eslint, prettier, and editorconfig to latest stable.

Modify bundler (rollup) to no longer run eslint(). This was primarily done
to eliminate an error from rollup-plugin-eslint:
  plugin eslint TypeError: Error while loading rule 'prettier/prettier':
  context.getPhysicalFilename is not a function

Note that eslint/prettier work fine when run via CLI and within VS code, and
they're still part of the CI pipeline, but they're no longer required to pass
in order to get the build artifacts.